name: Sync Backend Submodule

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 16 * * *" # Runs every day at 16:00 UTC (18:00 CET)

env:
  SUBMODULE_NAME: "Backend"

jobs:
  sync-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
          ref: 'main'
          fetch-depth: 0


      - name: Update Backend submodule to latest commit
        run: git submodule update --remote --merge ${{ env.SUBMODULE_NAME }}

      - name: Commit and push Backend submodule update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ env.SUBMODULE_NAME }}
          git commit -m "Update Backend submodule to latest commit" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
