name: Sync Frontend Submodule

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 16 * * *" # Runs every day at 16:30 UTC (18:30 CET)

env:
  SUBMODULE_NAME: "Frontend"

jobs:
  sync-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update Frontend submodule to latest commit
        run: git submodule update --remote --merge ${{ env.SUBMODULE_NAME }}

      - name: Commit and push Frontend submodule update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ env.SUBMODULE_NAME }}
          git commit -m "Update Frontend submodule to latest commit" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
